openapi: 3.0.3
info:
  title: User Auth API
  version: "1.0.0"
paths:
  /users:
    post:
      tags:
        - User
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
    get:
      tags:
        - User
      operationId: getUser
      parameters:
        - name: id
          in: query
          required: false
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserDto'
    put:
      tags:
        - User
      operationId: updateUser
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserDto'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserDto'
  /users/login:
    post:
      tags:
        - User
      operationId: login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
  /users/refresh-token:
    post:
      tags:
        - User
      operationId: refreshToken
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RefreshTokenRequest'
      responses:
        '200':
          description: Token refreshed successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthResponse'
components:
  schemas:
    UserDto:
      type: object
      properties:
        id:
          type: long
        userName:
          type: string
        email:
          type: string
        password:
          type: string
      required:
        - userName
        - email
        - password
    LoginRequest:
      type: object
      properties:
        userName:
          type: string
        password:
          type: string
      required:
        - userName
        - password
    AuthResponse:
      type: object
      properties:
        token:
          type: string
        expiresIn:
          type: integer
          description: Expiration time in seconds
      required:
        - token
        - expiresIn
    RefreshTokenRequest:
      type: object
      properties:
        refreshToken:
          type: string
      required:
        - refreshToken
