spring:
  application:
    name: userauth
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/energy-dev}
  datasource:
    username: userauthuser
    password: userauthpassword
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

logging:
  level:
    org.springframework.security: INFO

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    url: jdbc:postgresql://userauthdb-service:5432/userauthdb

---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:postgresql://localhost:5432/userauthdb
