apiVersion: v1
kind: ConfigMap
metadata:
  name: userauth-config
  namespace: energyco
data:
  SPRING_PROFILES_ACTIVE: "prod"
  DB_HOST: "userauthdb-service"
  DB_PORT: "5432"
  LOG_LEVEL: "INFO"
  KEYCLOAK_ISSUER_URI: "http://keycloak.security.svc.cluster.local:8080/realms/energy-dev"
