apiVersion: v1
kind: Service
metadata:
  name: userauthdb-service
  namespace: energyco
spec:
  selector:
    app: userauthdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
