apiVersion: v1
kind: Service
metadata:
  name: userauth-service
  namespace: energyco
spec:
  selector:
    app: userauth
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
