name: CI/CD Pipeline

on:
  push:
    branches:
      - master
      - developer

jobs:
  build-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        run: |
          docker build -t victodomvar/userauth:latest .
          docker push victodomvar/userauth:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.32.0'

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment/userauth-deployment.yaml --validate=false
          kubectl apply -f k8s/deployment/userauth-service.yaml --validate=false
          kubectl wait --for=condition=ready pod -l app=userauth -n energyco
